<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Connexion</title>
</head>

<body>
    <h1>Connexion</h1>
    <form method="POST" action="index.php">
        <label>Identifiant :</label><br>
        <input type="text" name="identifiant" required><br><br>

        <label>Mot de passe :</label><br>
        <input type="password" name="password" required><br><br>

        <button type="submit">Se connecter</button>
    </form>
    <?php if (isset($error)) { ?>
        <?= $error ?>
    <?php } ?>


</body>

</html>