<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <a href="index.php">Catégories</a>
        </nav>
    </header>
    
    <main>
        <?php include $template ?>
    </main>
    
</body>
</html>