<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>Quiz PHP</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>

    <form class="quiz">
        <fieldset class="list-answers">
            <legend>
                <?= $quiz['question']; ?>
            </legend>
            <?php foreach ($quiz['answers'] as $answer): ?>
                <?php if ($answer === $quiz['correct_answer']): ?>
                <label class="container"><?= $answer; ?>
                    <input type="radio" class="goodOne" name="answer" value="<?= $answer; ?>" checked></input>
                </label>
                <?php else: ?>
                <label class="container"><?= $answer; ?>
                    <input type="radio" name="answer" value="<?= $answer; ?>"></input>
                </label>
                <?php endif; ?>
            <?php endforeach; ?>
        </fieldset>
    </form>

</body>

</html>