<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
</head>
<body>

    <div class="container_cat">
        <?php foreach($categories as $categorie): ?>
            <p class="cat"><a href="categorie.php?id=<?= $categorie['id'] ?>"><?= $categorie['title'] ?></a></p>
        <?php endforeach; ?>
    </div>
    
</body>
</html>