<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/styles.css">

    <title>Connexion</title>
</head>

<body>

    <h1>Connexion</h1>
    <div class="container">
        <form method="post" action="index.php">
            <label for="identifiant">Identifiant :</label>
            <input type="text" id="identifiant" name="identifiant" required>

            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>

            <input type="submit" value="Se connecter">
        </form>
    </div>
    <?php if (isset($error)) : ?>
        <div class="error">
            <p><?= $error; ?></p>
        </div>
    <?php endif; ?>

</body>

</html>