<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/styles.css">

    <title>Code Secret</title>
</head>

<body>

    <div class="secret-container">

        <h1>Code secret : <a class="highlight" href="#"><span>PHP ROCKS !</span></a></h1>

        <a href="logout.php">Se déconnecter</a>

    </div>

</body>

</html>